/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnotationPopup: typeof import('./components/Tooltip/AnnotationPopup.vue')['default']
    ConnectionDialog: typeof import('./components/DrawToolbar/ConnectionDialog.vue')['default']
    ConnectivityGraph: typeof import('./components/ConnectivityGraph/ConnectivityGraph.vue')['default']
    CopyToClipboard: typeof import('./components/CopyToClipboard/CopyToClipboard.vue')['default']
    DrawToolbar: typeof import('./components/DrawToolbar/DrawToolbar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconAim: typeof import('@element-plus/icons-vue')['Aim']
    ElIconArrowDown: typeof import('@element-plus/icons-vue')['ArrowDown']
    ElIconArrowUp: typeof import('@element-plus/icons-vue')['ArrowUp']
    ElIconClose: typeof import('@element-plus/icons-vue')['Close']
    ElIconCopyDocument: typeof import('@element-plus/icons-vue')['CopyDocument']
    ElIconDelete: typeof import('@element-plus/icons-vue')['Delete']
    ElIconEdit: typeof import('@element-plus/icons-vue')['Edit']
    ElIconFinished: typeof import('@element-plus/icons-vue')['Finished']
    ElIconLock: typeof import('@element-plus/icons-vue')['Lock']
    ElIconUnlock: typeof import('@element-plus/icons-vue')['Unlock']
    ElIconWarning: typeof import('@element-plus/icons-vue')['Warning']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ExternalResourceCard: typeof import('./components/Tooltip/ExternalResourceCard.vue')['default']
    HelpModeDialog: typeof import('./components/HelpModeDialog/HelpModeDialog.vue')['default']
    ProvenancePopup: typeof import('./components/Tooltip/ProvenancePopup.vue')['default']
    Tooltip: typeof import('./components/Tooltip/Tooltip.vue')['default']
    TreeControls: typeof import('./components/TreeControls/TreeControls.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
